# yaml-language-server: $schema=https://json.schemastore.org/commitlintrc.json

# Prefixes:
#   build     | chore   | ci    | docs  | feat  | fix
#   refactor  | revert  | style | test  | perf

extends: ['@commitlint/config-conventional']
