name: Github Pages Astro CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 17
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM 7
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7

      - name: Install Node dependencies
        run: pnpm install --recursive

      - name: Build Astro Website
        working-directory: ./demo
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/dist

      - name: Version updated package
        run: pnpm lerna version --conventional-commits --yes

      - name: Publish updated package
        run: pnpm lerna publish from-git
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
