name: Build and Deploy [PRODUCTION] to Netlify
on:
  push:
    branches: [master]
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      # ————————————————————————————————————————————————————————————————————————

      - name: Use Node.js 17
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Setup PNPM 7
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.0

      - name: Install Node dependencies
        # `production` to exclude dev. dependencies
        run: NODE_ENV=production pnpm install --recursive

      - name: Build Astro Website
        working-directory: ./demo
        run: pnpm run build

      # ————————————————————————————————————————————————————————————————————————

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.4
        with:
          publish-dir: './demo/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
